### ISSUE TITLE
I tried to run the Cloudy 2

### ISSUE THREAD

**Issue by leechitang** [Cloudy-Git/Cloudy#1]
Logger -- FXView Updater: Connection refused (Connection refused) -- 2017-09-26T21:11:32.222
java.net.ConnectException: Connection refused (Connection refused)

When I ran the cloudy 2 on Mac.  It gave me this error and it doesn't allow the gmail to connect.  It says connection refuse as well... Do you know why is it doing that?

I would also like to add that I'm running this on

OS X El Capitan
Version 10.11.6

**Comment by Cloudy-Git** [comment]
This issue has been fixed.

**Comment by leechitang** [comment]
Thanks

**Comment by leechitang** [comment]
I'll do more testing this week
